
import logging

from .api import LMAPI
from .config import PROMPTS


# Setting up the logger for this module
logger = logging.getLogger(__name__)


class Assistant:

    """
    An AI assistant that interacts with a LM API to provide various types of reviews and responses.
    """

    def __init__(self, api_url: str = None) -> None:
        """
        Initializes the Assistant with an optional API URL.

        Args:
            api_url (str, optional): The URL of the LM API. If not provided, a default URL is used.
        """

        # Initialize the LMAPI instance with the provided URL or use the default URL
        if api_url:
            self.lm_api = LMAPI(api_url)
            logging.debug(f"Initialized LMAPI with URL: {api_url}")
        else:
            self.lm_api = LMAPI()
            logging.debug("Initialized LMAPI with default URL")

        # Load predefined prompts from the configuration
        self.prompts = PROMPTS
        logging.debug("Loaded prompts from config")

    def get_response(self, prompt: list) -> str:
        """
        Sends a prompt to the API client and returns the response.

        Args:
            prompt (list): A list of dictionaries representing the conversation prompt.

        Returns:
            str: The response received from the API.
        """

        logging.debug(f"Sending prompt to API: {prompt}")
        response = self.lm_api.get_response(prompt) # Get the response from the LM API
        logging.debug(f"Received response from API: '{response}'")

        return response

    def review(self, category: str, data: str) -> str:
        """
        Generates a review for a given category based on the provided data by interacting with the LM API.

        Args:
            category (str): The type of review to generate.
            data (str): The input data or content that needs to be reviewed.

        Returns:
            str: The review generated by the LM API based on the provided category and data.
        """

        # Construct the prompt using system and user roles, incorporating the specified category and data
        prompt = [
            {"role": "system", "content": self.prompts.get("sys")},
            {"role": "user", "content": self.prompts.get(category).format(data=data)}
        ]

        logging.debug(f"Constructed prompt for category '{category}': {prompt}")

        # Generate the review by sending the prompt to the LM API
        file_review = self.get_response(prompt=prompt)
        logging.debug(f"Generated review for category '{category}': '{file_review}'")

        return file_review
